Azure/azure-functions-tooling-feed

- cli-feed-v3.json
> Update v1 to 1.0.15

- cli-feed-v3.json
> Fix syntax error

- cli-feed-v3.json
Corresponding host: https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12303
> Prerelease 2.4.321

- cli-feed-v3.json
> Minor update for signed bits

- cli-feed-v3.json
CLI version: 2.4.401
Host version: 2.0.12309
Template zip version: 2.0.10336
> 2.18.1 for preview

- cli-feed-v3.json
Runtime release is finished. Ready to release this.
> Release CLI 2.4.498

- cli-feed-v3.json
There were some formatting changes -- so ignore whitespace in review.
> updating cli-feed for 2.6.615

- cli-feed-v3.json
Doing prerelease first to ensure all is well
> Update CLI prerelease for Python hotfix

- cli-feed-v3.json
> Release Core Tools with fixes for Python

- cli-feed-v3.json
Feed update for 2.0.12673 runtime release
> core-tools 2.7.1623 release

- GenerateToolingFeed/Helper.cs
- GenerateToolingFeed/Program.cs
- azure-pipelines.yml
> Generate the tooling feed dynamically for v2 and v3

- GenerateToolingFeed/Program.cs
- cli-feed-v3-2.json
- cli-feed-v3.json
> Fixing the feed generation logic to use minified version of x64

- cli-feed-v3.json
Releasing version 1.0.29 added in https://github.com/Azure/azure-functions-tooling-feed/pull/208
> Release Version 1.0.29

- cli-feed-v3-3.json
- cli-feed-v4.json
Once this is settled on, approved and merged, we would need to complete these tasks--
> Add new feed for .NET 5

- cli-feed-v4.json
> Bump dotnet isolated templates

- cli-feed-v3.json
Sent the PR manually as automated step updated tp latest in the file - 3.0.27
> Update feed to release 3.0.3477

- .vscode/launch.json
- .vscode/tasks.json
- GenerateToolingFeed/Program.cs
- cli-feed-v4.json
And two changes to make it easier to debug this repo:
- Add VS Code config
- Get the "current" feed from the local repo instead of a GitHub url
> Add v4-prerelease tag

- cli-feed-v3.json
- cli-feed-v4.json
Due to https://github.com/Azure/azure-functions-core-tools/issues/2989
> Revert recent v3 and v4 releases

- cli-feed-v4.json
> Updating Visual Studio Feed to reflect the .NET support

- cli-feed-v4.json
This reverts commit b315fd100d2c5228af7b0846620309b967683a08.
> Revert "Updated release version (#373)"

- cli-feed-v4.json
> Setting visibility of net 5 isolated to hidden

- cli-feed-v4.json
> Update v4 feed for new template packages

- cli-feed-v4.json
Resolves - #458 
Updating Netframework version to v7.0 for .NET 7 instead of v6.0
> Updating Netframework version to v7.0 for .NET 7 

- cli-feed-v4.json
Draft due to ongoing Core Tools release (this will need a rebase).
> Adding app setting for .NET LTS and STS isolated worker model

- cli-feed-v4.json
Link to release block diff:
https://gist.github.com/fabiocav/204bb4785212747e987a4e31680a2552/revisions
> Dropping preview qualification from .NET 8

- cli-feed-v4.json
Add 4.63.0 which fixes the trailing space for WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED app setting.
Diff between 4.62.0 and 4.63.0: https://gist.github.com/kshyju/6783e1ff2ff9b943a956ad3f2630e9ff/revisions
> Add 4.63.0 which fixes the trailing space for WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED app setting

- cli-feed-v4.json
Move 4.67.0 from pre-release to GA.
> Update v4 release to 4.67

- cli-feed-v4.json
https://gist.github.com/v-smanchem/4e59bb17e72cf1b58d26e93c0dbdb9d0
> Updating feed for (4.0.5530)

- cli-feed-v3.json
- cli-feed-v4.json
https://gist.github.com/v-smanchem/e09379ec692358d3ff245757fc5bb7b7 - cli-feed-v4.json
https://gist.github.com/v-imohammad/c6cdd7e76abb975113391789d885d807/revisions?diff=unified&w= -cli-feed-v3.json
> Updating feed for 3.21.1(3.0.5542)

- cli-feed-v4.json
https://gist.github.com/v-smanchem/fd68b47606c4096d07465c9920550324/revisions - cli-feed-v4.json
> Updating feed

- cli-feed-v4.json
https://gist.github.com/v-smanchem/85ff978d1eb8d55c652cfdadf3717c2a
> Updating feed for 4.30.0 coretools

- cli-feed-v4.json
https://gist.github.com/v-smanchem/7e7efb8074775cc60007d9a1d8f77322 - cli-feed-v4.json
> Updating feed 4.31.1 Coretools

- cli-feed-v4.json
https://gist.github.com/v-smanchem/df6b6ab55725792b3c00361dfccd742d
> Updating feed Core tools 4.31.1

- cli-feed-v3.json
- cli-feed-v4.json
https://gist.github.com/v-smanchem/c40755cd5becd7436bcc491b17bf9c39/revisions
> Updating feed 3.22.0

- cli-feed-v4.json
https://gist.github.com/v-smanchem/13e7aa3688fd8482089f9d10ede29458/revisions
> Updating feed 4.33.2

- cli-feed-v4.json
Updating template reference to net core template package. Gist comparing the release update
https://gist.github.com/soninaren/b15bf39124354b2f7c91b77dd17ab422/revisions
> Updating template references for net core package to 4.0.3041

- cli-feed-v4.json
Comparison gist [here](https://gist.github.com/satvu/7e53bc08079b52101589643beefa5d53/revisions)
> Hide .NET8 Inproc

- cli-feed-v4.json
Removing Linux support temporarily.
Version diff: https://gist.github.com/mattchenderson/c3585d92f8daf91fb5a84cc3262ee0dd/revisions
Draft PR until I'm able to do an extra bit of validation.
> removing Linux support from in-proc .NET 8

- cli-feed-v4.json
https://gist.github.com/v-smanchem/a890a102f0ca332154bd97adc3b9e8e1/revisions
> Updating feed for 4.34.2
