Azure/azure-functions-tooling-feed

cli-feed-v3.json

Should we update to "Microsoft.NET.Sdk.Functions": "1.0.26"? Why haven't we updated it before?

Update CLI to 2.5.539

---

cli-feed-v3.json

There was a bug is CLI. We are able to skip OGFs run, this PR updates "release".

Updating CLI to 2.5.553

---

cli-feed-v3-2.json
cli-feed-v3.json

There's no change between 2.7.2100 and 2.7.2184 - https://github.com/Azure/azure-functions-core-tools/compare/2.7.2100...2.7.2184
This is because the update was in a release pipeline and we need to create new version to notify users.
I am not going through the usual E2E tests suite given there's no delta.

Update v2 release and preview

---

cli-feed-v3.json

I changed the `"cli"` cdn url and the `"sha2"` field, everything else was copied from the `1.12.0` entry

Updated prerelease to 1.13.0. Added 1.13.0 entry to reference CLI 1.0.28

---

cli-feed-v3.json

Release CLI Version 1.0.28 added in https://github.com/Azure/azure-functions-tooling-feed/pull/216

Release CLI Version 1.0.28

---

cli-feed-v3-2.json
cli-feed-v3.json

Will send a separate PR to update v3 templates after this is merged (since it looks like I can either upgrade only v2 or v3 at a time unless I'm missing something).

[v2] Updated templates to point to 2.1.1642

---

azure-pipelines.yml

Using `DownloadBuildArtifacts` fails if the build was re-attempted and didn't succeed the first time. We should use `DownloadPipelineArtifact`

Fix downloading from Core Tools pipeline

---

GenerateToolingFeed/Constants.cs
cli-feed-v4.json

To support Apple Silicon macs
I have to add the entry once manually, and going forward it should automatically be included in the generation logic. Including this with the release of https://github.com/Azure/azure-functions-tooling-feed/pull/325

Add arm64 entry

---

cli-feed-v4.json

Updating the feed to include .NET Framework & .NET 7 isolated for v4. Addresses this issue:
https://github.com/Azure/azure-functions-tooling-feed/issues/357

Feed update: Add .NET Framework & .NET 7 Isolated v4

---

GenerateToolingFeed/V4Format/V4FormatFeedEntryUpdater.cs

Allows the feed to generate new entries for Core Tools V4, which includes support for the .NET 7 and .NET Framework 4.8.

Add template prefix for net7-isolated and netfx-isolated

---

cli-feed-v4.json

Adds an entry for `min.win-arm64`. Subsequent releases should also include this entry after this PR is merged.

Add min.win-arm64 entry

---

cli-feed-v4.json

Fixes https://github.com/Azure/azure-functions-dotnet-worker/issues/1075
Added a new `endOfLifeDate` property under the `displayInfo` part of dotnet run time entries. We are exposing this as an optional property and will share that information with the consumers of this feed. No value for .NET Framework entry as we do not specify the version of .NET framework in the dropdown VS shows when creating a new function app.
This change is added in a patch version. So I cloned **4.26.0**, renamed to 4.26.1 and made the changes to those entries. Udpated the `tags=>v4-prerelease` element value to use this new patch version.
The date value used is ISO 8601 format version of dates (Printed using code like below in c#). 
````
var d = DateTime.SpecifyKind(new DateTime(2022, 10, 11), DateTimeKind.Utc); …
```

Added a new "endOfLifeDate" property for dotnet runtime entries.

---

cli-feed-v4.json

Fixes https://github.com/Azure/azure-functions-dotnet-worker/issues/1274
We will discuss (later) whether we should consider removing this entry altogether safely.
Created 3.47.1 from 3.47.0 and set hidden true for .NET Core 3.1. The .NET core 3.1 entry is only present in the c4 feed json.

Hide .NET Core 3.1 entry

---

cli-feed-v4.json

Fixes #452 
Updating prerelease tag to 4.43.0 which contains the entry for net8. Validated locally.

Updating prerelease tag to 4.43.0 which contains the entry for net8

---

cli-feed-v4.json

Updating pre-release tag to 4.44.0 which includes the net8 entry using 4.0.2718 version of project & item template.
- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ProjectTemplates/4.0.2718
- https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.ItemTemplates/4.0.2718
The new version of nuget package was built from these changes:
https://github.com/Azure/azure-functions-templates/commits/dev

Updating pre-release tag to 4.44.0 which includes the net8 entry using 4.0.2718 version of project & item template

---

cli-feed-v4.json

copy-paste of 4.47.0, copying over the change from https://github.com/Azure/azure-functions-tooling-feed/commit/862188a0c8da0dba93e29e754030e0970c19175a but updating the version specified for the templates. I also set the hidden tag to false. While in draft mode, this will only include the prerelease pointer for a quick validation. For full PR we will add to the regular v4 entry.

adding net8 back

---

cli-feed-v4.json

Update includes changes from [this templates PR](https://github.com/Azure/azure-functions-templates/pull/1495) which introduces two new templates packages, one for NetFx and one for NetCore apps.
EDIT: @mattchenderson validated that this is picked up correctly by VS by pointing to this feed PR locally. 
Diff of 4.66.0 and 4.67.0: https://gist.github.com/satvu/47d75bfe4569f0623f7a4345e9a1fe59/revisions

Update dotnet-isolated project and item templates

---

GenerateToolingFeed/Constants.cs
GenerateToolingFeed/FeedEntryUpdaterFactory.cs
GenerateToolingFeed/Helper.cs
GenerateToolingFeed/Program.cs
GenerateToolingFeed/V4Format/V4FormatFeedEntryUpdater.cs
cli-feed-v4.json

https://gist.github.com/soninaren/84e4e139554c48e4cf38d93e12baaab3/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2

adding v0 release to feed

---

cli-feed-v4.json

Unhiding the v0 tag and the .NET 8 in-process model release.
Diff gist between 4.80.0/4.80.0-inproces and 4.81.0/4.81.0-inprocess: https://gist.github.com/mattchenderson/128cecff83186d510243c1f909639cc2/revisions

Unhiding .NET 8 in-proc for Windows

---

cli-feed-v4.json

gist for changes between 4.82.0-inprocess and 4.83.0-inprocess
[Revisions · updating tooling feed to 4.83.0-inprocess (github.com)](https://gist.github.com/arroyc/dfd31f5e341f71a51fbf3f7c7204273e/revisions)

Updating feed
